### ISSUE TITLE
Specify with which rustc version binaries are built

### ISSUE THREAD

**Issue by adrianheine** [oakes/SolidOak#11]
Since `rustc` moves so quickly currently, it's usually not sufficient to just have a relatively current version to run `SolidOak`. With `rustc` from 2015-03-05 (rust-lang/rust@3b3bb0e) and 2015-03-12 (rust-lang/rust@425297a) for example, I get the following linking errors when running `SolidOak` 0.1:

```
./solidoak-0.1.0-linux.bin: symbol lookup error: ./solidoak-0.1.0-linux.bin: undefined symbol: _ZN3str28Utf8Error...core..fmt..Debug3fmt20h01053e69e48290fe51yE
```

**Comment by oakes** [comment]
Thank you for pointing that out. I have removed the binary and changed the readme to say that building from source is required for now.
