### ISSUE TITLE
Font isue on OSX Mavericks

### ISSUE THREAD

**Issue by AlisdairO** [oakes/SolidOak#13]
Hi - I installed the prebuilt OSX 0.1.1 binary at https://sekao.net/solidoak/ onto OSX Mavericks.  Upon running it I get a screen like the following.  I was wondering if you're perhaps using a font I'm missing due to being back a version of the OS?

![solidoak](https://cloud.githubusercontent.com/assets/6296622/6946620/94aee65a-d899-11e4-8214-f7ab8d88800f.png)

**Comment by oakes** [comment]
I must not be packaging something that is needed. Please try going to the app's parent directory in the terminal and running `./SolidOak.app/Contents/MacOS/solidoak`. That should make it output its errors into the terminal, so we can track down the problem.

**Comment by AlisdairO** [comment]
Hey, it looks like the following:

jury2-2:Applications alisdair$ ./SolidOak.app/Contents/MacOS/solidoak
2015-04-01 19:37:37.076 defaults[43231:507] 
The domain/default pair of (.GlobalPreferences, AppleCollationOrder) does not exist
./SolidOak.app/Contents/MacOS/solidoak: line 80: test: argument expected
2015-04-01 19:37:37.242 solidoak-bin[43223:d07] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

(<unknown>:43223): Pango-WARNING **: dlopen(/usr/local/Cellar/pango/1.36.7/lib/pango/1.8.0/modules/pango-basic-coretext.so, 2): image not found

(<unknown>:43223): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='latin'

(<unknown>:43223): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='common'

**Comment by oakes** [comment]
I uploaded a new binary. Please try downloading it again and let me know if it makes a difference.

**Comment by AlisdairO** [comment]
Same issue appears on the screen!

jury2-2:Applications alisdair$ ./SolidOak.app/Contents/MacOS/solidoak
2015-04-01 20:38:51.070 defaults[43649:507] 
The domain/default pair of (.GlobalPreferences, AppleCollationOrder) does not exist
./SolidOak.app/Contents/MacOS/solidoak: line 80: test: argument expected
2015-04-01 20:38:51.139 solidoak-bin[43641:d07] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

(<unknown>:43641): Pango-WARNING **: dlopen(/usr/local/Cellar/pango/1.36.7/lib/pango/1.8.0/modules/pango-basic-coretext.so, 2): image not found

(<unknown>:43641): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='latin'

(<unknown>:43641): Pango-WARNING **: failed to choose a font, expect ugly output. engine-type='PangoRenderCoreText', script='common'

**Comment by oakes** [comment]
OK I uploaded another binary. Please try again, and thank you for helping me with this.

**Comment by AlisdairO** [comment]
It's working!  Thank you very much for sorting it - looking forward to using it.

**Comment by oakes** [comment]
Great! The Mac version is definitely still a bit rough. I'm tracking all the OSX-specific problems in #1.
