### ISSUE TITLE
Instructions on how to enable autocomplete

### ISSUE THREAD

**Issue by hydrogen18** [oakes/SolidOak#15]
There does not appear to be any instructions on how to enable autocomplete.

**Comment by oakes** [comment]
Yeah I'll try to improve that soon. It just uses [Racer](https://github.com/phildawes/racer), so the Vim instructions in its README indicate how it works. Just type something like std::io::B and hit Ctrl+x Ctrl+o to see the list of completions.

**Comment by hydrogen18** [comment]
I get the following at the bottom of the editor when I do that.

```
-- Omni completion (^O^N^P) Pattern not found
```

**Comment by oakes** [comment]
Try deleting ~/.soak/plugin/racer.vim and restarting the app. If you used an older version of SolidOak, you may still have an old copy of it, which could prevent it from working.

**Comment by oakes** [comment]
Did that advice help or does the problem still exist after trying it?

**Comment by hydrogen18** [comment]
Well actually I gave up on Rust for now. I'm just going to wait till they have a '1.0' release that is stable.
