### ISSUE TITLE
Cannot compile using the nightly build

### ISSUE THREAD

**Issue by ozanerdem** [oakes/SolidOak#20]
This is what I get after `cargo build` on Ubuntu 15.04:

cargo build                                    
    Updating git repository `https://github.com/oakes/neovim-rs`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/oakes/gtk`
 Downloading libc v0.1.7
 Downloading pango v0.0.1
 Downloading glib v0.0.1
 Downloading pkg-config v0.3.4
 Downloading gcc v0.3.5
 Downloading gdk v0.1.0
 Downloading glib-sys v0.1.0
 Downloading c_vec v1.0.12
 Downloading cairo-rs v0.0.1
 Downloading bitflags v0.1.1
 Downloading cairo-sys-rs v0.1.0
 Downloading rustc-serialize v0.3.14
 Downloading gdk-sys v0.1.0
 Downloading pango-sys v0.1.0
   Compiling solidoak v0.1.3 (file:///home/ozan/SolidOak)
   Compiling neovim-rs v0.1.0 (https://github.com/oakes/neovim-rs#c7fdca00)
   Compiling pkg-config v0.3.4
   Compiling libc v0.1.7
   Compiling gcc v0.3.5
   Compiling c_vec v1.0.12
   Compiling rustc-serialize v0.3.14
   Compiling bitflags v0.1.1
   Compiling gdk-sys v0.1.0
   Compiling pango-sys v0.1.0
   Compiling cairo-sys-rs v0.1.0
   Compiling glib-sys v0.1.0
   Compiling gtk-sys v0.1.0 (https://github.com/oakes/gtk#aa9182a1)
   Compiling glib v0.0.1
   Compiling pango v0.0.1
   Compiling cairo-rs v0.0.1
   Compiling gdk v0.1.0
   Compiling gtk v0.0.1 (https://github.com/oakes/gtk#aa9182a1)
src/projects.rs:88:18: 88:35 error: mismatched types:
 expected `&gtk::widgets::window::Window`,
    found `gtk::widgets::window::Window`
(expected &-ptr,
    found struct `gtk::widgets::window::Window`) [E0308]
src/projects.rs:88             Some(ui.window.clone()),
                                    ^~~~~~~~~~~~~~~~~
note: in expansion of if let expansion
src/projects.rs:87:9: 109:10 note: expansion site
note: in expansion of if let expansion
src/projects.rs:86:5: 110:6 note: expansion site
src/projects.rs:88:18: 88:35 help: pass `--explain E0308` to see a detailed explanation
src/ui.rs:40:45: 40:53 error: type `gtk::widgets::tree_iter::TreeIter` does not implement any method in scope named `unwrap`
src/ui.rs:40     let mut iter = widgets::TreeIter::new().unwrap();
                                                         ^~~~~~~~
src/ui.rs:74:45: 74:53 error: type `gtk::widgets::tree_iter::TreeIter` does not implement any method in scope named `unwrap`
src/ui.rs:74     let mut iter = widgets::TreeIter::new().unwrap();
                                                         ^~~~~~~~
src/utils.rs:176:45: 176:53 error: type `gtk::widgets::tree_iter::TreeIter` does not implement any method in scope named `unwrap`
src/utils.rs:176     let mut iter = widgets::TreeIter::new().unwrap();
                                                             ^~~~~~~~
error: aborting due to 4 previous errors
Could not compile `solidoak`.

To learn more, run the command again with --verbose.

**Comment by oakes** [comment]
Yeah there were some breaking changes in the gtk library. I just fixed the ones you mentinoed but there are more that I need to fix. I'll try to do that tonight.

**Comment by oakes** [comment]
If you do a `cargo update` it should build now.
