### ISSUE TITLE
SolidOak crashes when I press "New project" or "Import" buttons

### ISSUE THREAD

**Issue by vi** [oakes/SolidOak#23]
```
$ /home/nix/SolidOak/target/debug/solidoak 

(process:18872): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.

** (solidoak:18872): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(solidoak:18872): GLib-GIO-ERROR **: attempting to create schema 'org.gtk.Settings.FileChooser' without a path
Trace/breakpoint trap
```

SolidOak 0.1.3-10-g52807ce is built against NixOS's 64-bit packages without modifications to source code or depenencies.

**Comment by oakes** [comment]
The Linux version doesn't bundle GTK 3.10, so make sure that is installed. This error appears to indicate you don't have the necessary GLib schema files. Normally these are installed in the system, such as `/usr/share/glib-2.0/schemas` in the case of Ubuntu.

**Comment by oakes** [comment]
If this is still an issue for you, please let me know.
