### ISSUE TITLE
SolidOak quit unexpectedly.

### ISSUE THREAD

**Issue by soulfly** [oakes/SolidOak#24]
Can't run the latest version from site on my OS X 10.10.3

Got an error:

     Click Reopen to open the application again. Click Report to see more detailed information and send a report to Apple.

**Comment by oakes** [comment]
I believe this is a duplicate of #16.

**Comment by jjtuttle** [comment]
Same issue with me too since I took on the seed for OS X 10.10.4

OS X 10.10.3 worked perfect....
