### ISSUE TITLE
 unresolved import `gdk::Rectangle`. There is no `Rectangle` in `gdk`

### ISSUE THREAD

**Issue by Botev** [oakes/SolidOak#25]
When I try to build it I get the following errors:

master/src/signal.rs:16:5: 16:14 error: unresolved import `gdk::Rectangle`. There is no `Rectangle` in `gdk`
/home/alex/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/src/signal.rs:16     Rectangle, Screen,
                                                                                 ^~~~~~~~~
master/src/signal.rs:105:27: 105:36 error: unresolved import `gdk::Rectangle`. There is no `Rectangle` in `gdk`
/master/src/signal.rs:105         EventWindowState, Rectangle, Screen,
                                                                                                        ^~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `gtk`.

**Comment by oakes** [comment]
Looks like I just needed to update my gtk fork. If you run a `cargo update` and then build again it should work now.
