### ISSUE TITLE
Get bulding on stable rust

### ISSUE THREAD

**Issue by kvark** [oakes/SolidOak#27]
Currently getting this error:
>/home/kvark/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/src/lib.rs:37:1: 37:25 error: unstable feature
/home/kvark/.cargo/git/checkouts/gtk-38cf3f4d9926c12a/master/src/lib.rs:37 #![feature(collections)]

**Comment by oakes** [comment]
This is now fixed.
