### ISSUE TITLE
compiling on openSUSE 13.2/ vte-2.91

### ISSUE THREAD

**Issue by oprudkyi** [oakes/SolidOak#41]
opensuse provides vte-2.91 by default but solidoak doesn't support it

   Compiling gdk v0.1.1 (https://github.com/rust-gnome/gdk#6c996c98)
Build failed, waiting for other jobs to finish...
failed to run custom build command for `gtk-sys v0.1.3 (https://github.com/oakes/gtk#38fca97c)`
Process didn't exit successfully: `SolidOak/target/debug/build/gtk-sys-9bdd8b518517f944/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/lib64
cargo:rustc-link-lib=gtk-3
cargo:rustc-link-lib=gdk-3
cargo:rustc-link-lib=pangocairo-1.0
cargo:rustc-link-lib=pango-1.0
cargo:rustc-link-lib=atk-1.0
cargo:rustc-link-lib=cairo-gobject
cargo:rustc-link-lib=cairo
cargo:rustc-link-lib=gdk_pixbuf-2.0
cargo:rustc-link-lib=gio-2.0
cargo:rustc-link-lib=gobject-2.0
cargo:rustc-link-lib=glib-2.0
cargo:rustc-cfg=gtk_3_6
cargo:rustc-cfg=gtk_3_8
cargo:rustc-cfg=gtk_3_10
cargo:rustc-cfg=gtk_3_12
cargo:rustc-cfg=gtk_3_14
cargo:cfg=gtk_3_6 gtk_3_8 gtk_3_10 gtk_3_12 gtk_3_14

--- stderr
thread '<main>' panicked at '`"pkg-config" "--libs" "--cflags" "vte-2.90"` did not exit successfully: exit code: 1
--- stderr
Package vte-2.90 was not found in the pkg-config search path.
Perhaps you should add the directory containing `vte-2.90.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vte-2.90' found
', ~/.cargo/git/checkouts/gtk-61164953be1831c6/master/gtk-sys/build.rs:45

trying to cheat system via mv vte-2.91.pc vte-2.90.pc won't help either 
   Compiling solidoak v0.1.3 (file://SolidOak)
error: linking with `cc` failed: exit code: 1
note: "cc" "-Wl,--as-needed" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "SolidOak/target/debug/solidoak.0.o" "-o" "SolidOak/target/debug/solidoak" "-Wl,--whole-archive" "-l" "morestack" "-Wl,--no-whole-archive" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "SolidOak/target/debug/deps/libneovim-6bdf0afeabbce483.rlib" "SolidOak/target/debug/deps/libgtk-2c0fd9e6ef856ab5.rlib" "SolidOak/target/debug/deps/libpango-815d63bae6e97b16.rlib" "SolidOak/target/debug/deps/libgtk_sys-9bdd8b518517f944.rlib" "SolidOak/target/debug/deps/libgdk-a7be0824891fd468.rlib" "SolidOak/target/debug/deps/libgdk_sys-90b3e7ec4683be4f.rlib" "SolidOak/target/debug/deps/libbitflags-dd68b8369bcd8ff0.rlib" "SolidOak/target/debug/deps/libcairo-ae793e6223f5b805.rlib" "SolidOak/target/debug/deps/libglib-06dda2a99b4e937f.rlib" "SolidOak/target/debug/deps/libcairo_sys-ce4b015e84866ded.rlib" "SolidOak/target/debug/deps/libc_vec-944f3e3f45efffaf.rlib" "SolidOak/target/debug/deps/librustc_serialize-c1e8163a38ed3d54.rlib" "SolidOak/target/debug/deps/libpango_sys-da64256c4978ada1.rlib" "SolidOak/target/debug/deps/libglib_sys-74b0b5bce7afd38b.rlib" "SolidOak/target/debug/deps/liblibc-ef5cbad4ef5c7a1e.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-198068b3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-198068b3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-198068b3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-198068b3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-198068b3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-198068b3.rlib" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-198068b3.rlib" "-L" "SolidOak/target/debug" "-L" "SolidOak/target/debug/deps" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "/usr/lib64" "-L" "SolidOak/target/debug/build/gtk-sys-9bdd8b518517f944/out" "-L" "~/.cargo/git/checkouts/neovim-rs-a70c241027c677cc/master/neovim/build/lib" "-L" "~/.cargo/git/checkouts/neovim-rs-a70c241027c677cc/master/neovim/.deps/usr/lib" "-L" "/usr/lib64" "-L" "/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "SolidOak/.rust/lib/x86_64-unknown-linux-gnu" "-L" "SolidOak/lib/x86_64-unknown-linux-gnu" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-l" "util" "-l" "nvim" "-l" "gtk-3" "-l" "gdk-3" "-l" "pangocairo-1.0" "-l" "pango-1.0" "-l" "atk-1.0" "-l" "cairo-gobject" "-l" "cairo" "-l" "gdk_pixbuf-2.0" "-l" "gio-2.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "vte-2.91" "-l" "gtk-3" "-l" "gdk-3" "-l" "pangocairo-1.0" "-l" "pango-1.0" "-l" "atk-1.0" "-l" "cairo-gobject" "-l" "cairo" "-l" "gdk_pixbuf-2.0" "-l" "gio-2.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "gdk-3" "-l" "pangocairo-1.0" "-l" "pango-1.0" "-l" "gdk_pixbuf-2.0" "-l" "cairo-gobject" "-l" "cairo" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "cairo" "-l" "pango-1.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "gio-2.0" "-l" "gobject-2.0" "-l" "glib-2.0" "-l" "c" "-l" "m" "-l" "dl" "-l" "pthread" "-l" "rt" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: SolidOak/target/debug/deps/libgtk-2c0fd9e6ef856ab5.rlib(gtk-2c0fd9e6ef856ab5.0.o): in function «gtk::widgets::vte_terminal::VteTerminal::fork_command»:
~/.cargo/git/checkouts/gtk-61164953be1831c6/master/src/widgets/vte_terminal.rs:79: unknown reference to symbol «vte_terminal_fork_command_full»
SolidOak/target/debug/deps/libgtk-2c0fd9e6ef856ab5.rlib(gtk-2c0fd9e6ef856ab5.0.o): in function «gtk::widgets::vte_terminal::VteTerminal::set_pty»:
~/.cargo/git/checkouts/gtk-61164953be1831c6/master/src/widgets/vte_terminal.rs:103: unknown reference to symbol «vte_terminal_set_pty_object»
SolidOak/target/debug/deps/libgtk-2c0fd9e6ef856ab5.rlib(gtk-2c0fd9e6ef856ab5.0.o): in function «gtk::widgets::vte_pty::VtePty::new»:
~/.cargo/git/checkouts/gtk-61164953be1831c6/master/src/widgets/vte_pty.rs:24: unknown reference to symbol «vte_pty_new»
collect2: error: ld returned 1 exit status

though, installing old vte (0.36.4) helps

**Comment by oakes** [comment]
I'm still working on getting the latest version of libvte to work with SolidOak, but it should work with version 0.36 as you mentioned.

**Comment by sunnystormy** [comment]
@oakes I'm having a similar issue, except with OpenSUSE Tumbleweed. In my case, the "cargo build" process never even exited after throwing an error. : /

**Comment by oakes** [comment]
I've updated the deps, it should now build with vte-2.91.
