### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by Nokel81** [oakes/SolidOak#49]
I did a git clone of the repo after installing the dependencies via apt-get. Then I did a cargo build and I got these errors:
src/utils.rs:123:22: 123:36 error: use of undeclared type name `widgets::Stack` [E0412]
src/utils.rs:123     pub build_terms: widgets::Stack
                                      ^~~~~~~~~~~~~~
src/utils.rs:123:22: 123:36 help: run `rustc --explain E0412` to see a detailed explanation
src/main.rs:108:23: 108:42 error: failed to resolve. Could not find `Stack` in `gtk::widgets` [E0433]
src/main.rs:108     let build_terms = widgets::Stack::new().unwrap();
                                      ^~~~~~~~~~~~~~~~~~~
src/main.rs:108:23: 108:42 help: run `rustc --explain E0433` to see a detailed explanation
src/main.rs:108:23: 108:42 error: unresolved name `widgets::Stack::new` [E0425]
src/main.rs:108     let build_terms = widgets::Stack::new().unwrap();
                                      ^~~~~~~~~~~~~~~~~~~
src/main.rs:108:23: 108:42 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 3 previous errors
Could not compile `solidoak`.

To learn more, run the command again with --verbose.

**Comment by oakes** [comment]
It looks like you may have an old version of GTK. I believe you need at least version 3.10.

**Comment by Nokel81** [comment]
The thing is that if I go to https://packages.debian.org/source/wheezy/gtk+3.0 and I run
apt-get install libgtx-3-0

I get libgtk-3-0 is already the newest version. I am using KDE if that makes any difference

**Comment by oakes** [comment]
According to that site, libgtk is only [version 3.4](https://packages.debian.org/wheezy/libgtk-3-0). That's weird, because I have a machine running Ubuntu 14.04 and it has libgtk 3.10.8 on it. For some reason, your apt-get repo is providing an older version that mine. Please run `pkg-config --modversion gtk+-3.0` so we can verify what version has been installed on yours.

**Comment by Nokel81** [comment]
I have 3.4.2, as per the command

**Comment by oakes** [comment]
Yeah it looks like if you update to jessie you'll be able to get [3.14](https://packages.debian.org/source/jessie/gtk+3.0).
