### ISSUE TITLE
Failed to build on CentOS 7.1

### ISSUE THREAD

**Issue by sunnystormy** [oakes/SolidOak#50]
I've attempted to build both the master and 0.1.3 releases on my CentOS machine.

Building for 0.1.3 ends with:

> Package `gtk v0.0.6 (https://github.com/oakes/gtk#3064a74b)` does not have these features: `gtk_3_10`

Building for master ends with:

>failed to run custom build command for `solidoak v0.1.3 (file:///home/michael/Downloads/SolidOak-master)`
Process didn't exit successfully: `/home/michael/Downloads/SolidOak-master/target/debug/build/solidoak-175e338a34a73716/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', ../src/libcore/result.rs:741

All of my dependencies are up to date. Please let me know if I'm missing something. Thank you.

**Comment by oakes** [comment]
I haven't tried building on CentOS so I don't know the specific issue here. However, I made a small change to the build script so please try building with the latest change to see if it makes a difference.

**Comment by sunnystormy** [comment]
@oakes 

Just to be clear, do you mean to try building again with the master branch?

**Comment by oakes** [comment]
Yep, I'm just curious if the build script itself was causing the issue.

**Comment by oakes** [comment]
Also, please make sure you have the latest version of rust installed.

**Comment by sunnystormy** [comment]
I do. I'll try building again in the near future and post my results. Thanks for your help!

**Comment by skrzepto** [comment]
master branch works for me but release 0.1.3 fails to compile for me as well

**Comment by oakes** [comment]
Yeah old releases will definitely not build anymore.
