### ISSUE TITLE
Doesn't build on Debian

### ISSUE THREAD

**Issue by alexkingnz** [oakes/SolidOak#58]
I have a Debian (mostly) Jessie system.  neovim didn't build, so I cloned and built it separately, as suggested.

The reason it didn't build was I didn't have the libtool executable.  See http://superuser.com/questions/928653/libtool-installed-but-not-found-in-usr-bin

The libtool executable is in the libtool-bin package, not the libtool package.

So I suggest the following fix to the docs to fix that:

diff --git a/README.md b/README.md
index 559f36d..3987a90 100644
--- a/README.md
+++ b/README.md
@@ -21,7 +21,7 @@ Note: If neovim fails to build, try [cloning it directly](https://github.com/oak
 
 ```Shell
 apt-get install libgtk-3-dev libglib2.0-dev libcairo2-dev libvte-2.90-dev
-apt-get install libtool autoconf automake cmake libncurses5-dev g++ pkg-config unzip
+apt-get install libtool-bin autoconf automake cmake libncurses5-dev g++ pkg-config unzip
 cargo build --release
 ```

**Comment by oakes** [comment]
Thanks, I added the change to the readme.
