### ISSUE TITLE
getting started with Rust - failed to install SolidOak

### ISSUE THREAD

**Issue by Paul-Yuchao-Dong** [oakes/SolidOak#62]
Downloaded binary from [website](https://github.com/oakes/SolidOak/releases/download/0.1.3/solidoak-0.1.3-linux.tar.gz).

Unarchived the gz file and then I tried to run the run.sh, after chmod +x it, with `./run.sh`, and it complained: `/home/paul/Downloads/solidoak-0.1.3-linux/bin/solidoak: error while loading shared libraries: libvte2_90.so.9: cannot open shared object file: No such file or directory`.

I'm using Ubuntu 16.04, just installed rustc 1.14.0 (e8a012324 2016-12-16) happy to post any further debugging info. 

Just want to get started with this exciting new language, any help is appreciated.

Merry Christmas and happy holidays, thanks you all for the good work.

**Comment by oakes** [comment]
I uploaded a new zip that I believe fixes the issue. It is at the same URL. Please give it a go and let me know if you still have issues.

**Comment by Paul-Yuchao-Dong** [comment]
sorry for the late reply, was on vacation. Tried the new release and works like a charm. Thank you for your help and great software!
