### ISSUE TITLE
home brew install fails

### ISSUE THREAD

**Issue by naveensrinivasan** [oakes/SolidOak#7]
When i try to run `brew install gtk+3 vte3 --without-x11` I get this as response  
`
➜  ~  brew install gtk+3 vte3 --without-x11
cairo: Unsatisfied dependency: XQuartz 0.0.0
Homebrew does not package XQuartz. Installers may be found at:
  https://xquartz.macosforge.org
pango: Unsatisfied dependency: XQuartz 0.0.0
Homebrew does not package XQuartz. Installers may be found at:
  https://xquartz.macosforge.org
at-spi2-core: Unsatisfied dependency: XQuartz 0.0.0
Homebrew does not package XQuartz. Installers may be found at:
  https://xquartz.macosforge.org
Error: Unsatisified requirements failed this build.
`

What is wrong?

Thanks

**Comment by oakes** [comment]
You need to install XQuartz as it mentions. It doesn't actually get used, but the homebrew formula requires it.

**Comment by naveensrinivasan** [comment]
Thanks! Got it!
