### ISSUE TITLE
Can't build from tar.gz or zip

### ISSUE THREAD

**Issue by beatgammit** [oakes/SolidOak#8]
$ wget https://github.com/oakes/SolidOak/archive/0.1.0.tar.gz
    $ tar -xzf 0.1.0.tar.gz
    $ cd SolidOak-0.1.0
    $ cargo build
    ...
    src/utils.rs:30:20 30:76 error: couldn't read resources/soak/after/syntax/rust.vim ...
    ...

It looks like `resources/soak` is empty, so perhaps whatever you're using to create the source packages isn't doing a `git submodule init && git submodule update`? Building from master works.

**Comment by oakes** [comment]
Github makes the source archives automatically, so I'm not sure what to do about that.

**Comment by oakes** [comment]
I'll close for now, but if you know of a way to adjust how Github creates the archives then please let me know.

**Comment by beatgammit** [comment]
I think the only real way of doing this is to put some tooling in build.rs to pull down an archive of soak if soak is going to remain a separate repository.

I built an [AUR package](https://aur.archlinux.org/packages/solidoak-git/) for git head, but this prevented me from making one based on your 0.1.0 release. Maybe later...
