### ISSUE TITLE
Conserned about use of application specific RC file

### ISSUE THREAD

**Issue by JesseKPhillips** [oakes/SolidOak#9]
It seems odd to me that the application would utilize its own RC file for the editor. Unless this is specific to IDE configurations, like .gvimrc. I would expect a common RC file that all neoVim editors would utilizes. It is understandable for neoVim itself to not use or to use .vimrc. Feel free to close this if a .vimrc is already consulted.

**Comment by oakes** [comment]
Well the main reason is so I can populate it with Rust-specific settings without affecting the normal RC file you use for vim/neovim. I am not sure what standard practice is, but I figured if you really want to use a single file you can use a symlink.
